# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e1Ohs83rgeNpnb0shGgANLqzhO_9GhXT

[連結文字](https://)
"""

!pip install -q -r requirements.txt pyngrok

import subprocess

process = subprocess.Popen([
    "streamlit", "run", "app.py",
    "--server.port", "8501",
    "--server.headless", "true",
])
print("儀表板已啟動")

from pyngrok import ngrok

ngrok.kill()
ngrok.set_auth_token("3GIrUaKhce6Y6OtnB73x8ejSlyh_4whvQbgx1wrEdx2L5zutY")
tunnel = ngrok.connect(8501)
print("請開啟：", tunnel.public_url)

import gradio as gr
import pandas as pd
import matplotlib.pyplot as plt
import random
import time
from datetime import datetime

# =========================
# 全域資料設定
# =========================

emotion_labels = ["平靜", "愉悅", "緊張", "低落"]

emotion_colors = {
    "平靜": "藍色柔和漸層",
    "愉悅": "黃色 / 橘色暖色動畫",
    "緊張": "紅色脈衝動畫",
    "低落": "紫色 / 低亮度流動背景"
}

emotion_descriptions = {
    "平靜": "目前情緒較穩定，畫面使用柔和藍色與慢速呼吸動畫。",
    "愉悅": "目前情緒較正向，畫面使用暖色系與輕快動畫。",
    "緊張": "目前情緒波動較高，畫面使用紅色脈衝，但會避免過度閃爍。",
    "低落": "目前情緒偏低，畫面使用紫色或低亮度流動背景。"
}

# 儲存分析紀錄
records = []

# 系統狀態
system_status = {
    "calibrated": False,
    "paused": False,
    "display_mode": "儀表板模式",
    "subject_id": "SUBJECT_001"
}


# =========================
# 產生模擬 AI 情緒結果
# 之後可以換成模組二的結果
# =========================

def get_fake_emotion_result():
    """
    這裡目前是模擬 AI 情緒辨識結果。
    之後如果模組二完成，可以把這裡改成接收真正的模型輸出。
    """

    emotion = random.choice(emotion_labels)

    confidence = {
        "平靜": random.randint(10, 90),
        "愉悅": random.randint(10, 90),
        "緊張": random.randint(10, 90),
        "低落": random.randint(10, 90)
    }

    # 讓被選中的情緒信心度比較高
    confidence[emotion] = random.randint(75, 98)

    return emotion, confidence


# =========================
# 開始校正功能
# =========================

def start_calibration(subject_id):
    if subject_id.strip() == "":
        subject_id = "SUBJECT_001"

    system_status["subject_id"] = subject_id
    system_status["calibrated"] = True

    message = f"""
    校正完成！

    受試者編號：{subject_id}

    系統已建立個人化基準狀態。
    後續分析只會保存情緒結果與數值資料，不會保存原始影像。
    """

    return message


# =========================
# 暫停 / 繼續分析
# =========================

def toggle_pause():
    system_status["paused"] = not system_status["paused"]

    if system_status["paused"]:
        return "目前狀態：已暫停分析"
    else:
        return "目前狀態：分析中"


# =========================
# 切換展示模式
# =========================

def change_display_mode(mode):
    system_status["display_mode"] = mode
    return f"目前展示模式：{mode}"


# =========================
# 建立信心度長條圖
# =========================

def create_confidence_chart(confidence):
    df = pd.DataFrame({
        "情緒": list(confidence.keys()),
        "信心度": list(confidence.values())
    })

    fig, ax = plt.subplots(figsize=(6, 4))
    ax.bar(df["情緒"], df["信心度"])
    ax.set_ylim(0, 100)
    ax.set_title("即時情緒信心度")
    ax.set_xlabel("情緒類別")
    ax.set_ylabel("信心度 (%)")

    for i, value in enumerate(df["信心度"]):
        ax.text(i, value + 1, str(value) + "%", ha="center")

    return fig


# =========================
# 建立時間軸趨勢圖
# =========================

def create_trend_chart():
    if len(records) == 0:
        fig, ax = plt.subplots(figsize=(7, 4))
        ax.set_title("情緒時間軸趨勢")
        ax.set_xlabel("時間")
        ax.set_ylabel("情緒分數")
        ax.text(0.5, 0.5, "尚無資料", ha="center", va="center")
        return fig

    df = pd.DataFrame(records)

    emotion_score_map = {
        "低落": 1,
        "平靜": 2,
        "愉悅": 3,
        "緊張": 4
    }

    df["情緒分數"] = df["情緒"].map(emotion_score_map)

    fig, ax = plt.subplots(figsize=(8, 4))
    ax.plot(df["時間"], df["情緒分數"], marker="o")
    ax.set_title("情緒時間軸趨勢")
    ax.set_xlabel("時間")
    ax.set_ylabel("情緒狀態")
    ax.set_yticks([1, 2, 3, 4])
    ax.set_yticklabels(["低落", "平靜", "愉悅", "緊張"])
    plt.xticks(rotation=30)

    return fig


# =========================
# 視覺安全模式
# =========================

def visual_safety_mode(emotion):
    """
    避免動畫太快、對比太高。
    這裡用文字模擬安全模式控制。
    """

    if emotion == "緊張":
        return "已啟用視覺安全模式：降低紅色閃爍速度與畫面亮度變化。"
    else:
        return "視覺安全模式：正常。"


# =========================
# 更新儀表板
# =========================

def update_dashboard():
    if not system_status["calibrated"]:
        empty_confidence = {
            "平靜": 0,
            "愉悅": 0,
            "緊張": 0,
            "低落": 0
        }

        return (
            "尚未校正",
            "請先按下「開始校正」建立受試者基準狀態。",
            "尚未產生視覺展示",
            create_confidence_chart(empty_confidence),
            create_trend_chart(),
            "尚無資料"
        )

    if system_status["paused"]:
        return (
            "分析已暫停",
            "目前系統暫停更新情緒結果。",
            "畫面維持上一個狀態。",
            create_confidence_chart({"平靜": 0, "愉悅": 0, "緊張": 0, "低落": 0}),
            create_trend_chart(),
            "系統暫停中"
        )

    emotion, confidence = get_fake_emotion_result()

    now = datetime.now().strftime("%H:%M:%S")

    record = {
        "受試者編號": system_status["subject_id"],
        "時間": now,
        "情緒": emotion,
        "平靜信心度": confidence["平靜"],
        "愉悅信心度": confidence["愉悅"],
        "緊張信心度": confidence["緊張"],
        "低落信心度": confidence["低落"],
        "展示模式": system_status["display_mode"]
    }

    records.append(record)

    current_status = f"""
    目前情緒：{emotion}

    最高信心度：{confidence[emotion]}%

    受試者編號：{system_status["subject_id"]}

    展示模式：{system_status["display_mode"]}
    """

    visual_output = f"""
    螢幕視覺映射：

    {emotion_colors[emotion]}

    說明：
    {emotion_descriptions[emotion]}
    """

    safety_text = visual_safety_mode(emotion)

    return (
        emotion,
        current_status,
        visual_output,
        create_confidence_chart(confidence),
        create_trend_chart(),
        safety_text
    )


# =========================
# 匯出報告
# =========================

def export_report():
    if len(records) == 0:
        return None

    df = pd.DataFrame(records)

    filename = f"emotion_report_{system_status['subject_id']}.csv"
    df.to_csv(filename, index=False, encoding="utf-8-sig")

    return filename


# =========================
# Gradio 介面設計
# =========================

with gr.Blocks(title="情緒光譜 Dashboard") as demo:

    gr.Markdown("""
    # 情緒光譜：攝影機情緒螢幕互動系統

    ## 模組四：儀表板與後台管理功能

    本介面負責顯示即時情緒狀態、信心度、時間軸趨勢、系統控制與報告匯出。
    """)

    with gr.Row():
        subject_input = gr.Textbox(
            label="受試者匿名編號",
            value="SUBJECT_001"
        )

        calibration_button = gr.Button("開始校正")
        pause_button = gr.Button("暫停 / 繼續分析")

    calibration_result = gr.Textbox(
        label="校正狀態",
        lines=4
    )

    pause_status = gr.Textbox(
        label="系統狀態"
    )

    with gr.Row():
        display_mode = gr.Radio(
            choices=["儀表板模式", "全螢幕展示模式"],
            value="儀表板模式",
            label="展示模式"
        )

        mode_result = gr.Textbox(label="目前展示模式")

    gr.Markdown("## 即時情緒分析結果")

    with gr.Row():
        current_emotion = gr.Textbox(label="目前情緒")
        current_status = gr.Textbox(label="即時狀態", lines=8)

    visual_display = gr.Textbox(
        label="螢幕視覺展示說明",
        lines=8
    )

    safety_output = gr.Textbox(
        label="視覺安全模式",
        lines=3
    )

    with gr.Row():
        confidence_plot = gr.Plot(label="信心度長條圖")
        trend_plot = gr.Plot(label="情緒時間軸趨勢")

    update_button = gr.Button("更新情緒資料")

    gr.Markdown("## 報告匯出")

    export_button = gr.Button("匯出 CSV 報告")
    report_file = gr.File(label="下載報告")

    # 按鈕事件
    calibration_button.click(
        fn=start_calibration,
        inputs=subject_input,
        outputs=calibration_result
    )

    pause_button.click(
        fn=toggle_pause,
        inputs=None,
        outputs=pause_status
    )

    display_mode.change(
        fn=change_display_mode,
        inputs=display_mode,
        outputs=mode_result
    )

    update_button.click(
        fn=update_dashboard,
        inputs=None,
        outputs=[
            current_emotion,
            current_status,
            visual_display,
            confidence_plot,
            trend_plot,
            safety_output
        ]
    )

    export_button.click(
        fn=export_report,
        inputs=None,
        outputs=report_file
    )

demo.launch(share=True)